apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
- ../../base
- pvc.yaml

configMapGenerator:
- files:
  - application.yml
  name: 82240947-configmap

patchesStrategicMerge:
- deployment.yaml
- ingress.yaml

images:
- name: ceappacr.azurecr.io/82240947
  newTag: "202410310921"
