apiVersion: apps/v1
kind: Deployment
metadata:
  name: "a82240947"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "a82240947"
  template:
    metadata:
      labels:
        app: "a82240947"
    spec:
      imagePullSecrets:
        - name: regcred  # 추가된 부분
      containers:
        - name: "a82240947"
          image: epgbaseacr.azurecr.io/82240947:latest
          ports:
          - containerPort: 8080

