apiVersion : apps/v1
kind: Deployment
metadata:
  name: "a82240947" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "a82240947"
  template:
    metadata:
      labels:
        app: "a82240947" 
    spec:
      containers:
        - name: "a82240947" 
          image: ceappacr.azurecr.io/82240947
          ports:
          - containerPort: 8080
