name: Azure CI/CD Workflow

on: workflow_dispatch

env:
  IMAGE_NAME: 82240947

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Repository checkout
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      # JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Spring Boot 애플리케이션 패키징
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # ACR에 로그인
      - name: 'ACR login'
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login cepgbaseacr.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      # Docker 이미지 빌드 및 태깅
      - name: 'Build & Tag Image'
        run: |
          docker build -t cepgbaseacr.azurecr.io/${{ env.IMAGE_NAME }}:latest -f Dockerfile .
          docker tag cepgbaseacr.azurecr.io/${{ env.IMAGE_NAME }}:latest ${{ secrets.STAPACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      # STAPACR에 로그인
      - name: 'STAPACR login'
        run: |
          echo ${{ secrets.CI_ACR_PASSWORD }} | docker login ${{ secrets.STAPACR_LOGIN_SERVER }} --username ${{ secrets.CI_ACR_USERNAME }} --password-stdin

      # CI/CD ACR에 이미지 푸시
      - name: 'Push image'
        run: |
          docker push ${{ secrets.STAPACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

      # Kubernetes 인증 설정
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      # Kubernetes에 배포
      - name: Update Kubernetes resources
        run: |
          echo "`ls`"
          cd manifests/overlays/prod
          kustomize edit set image ${{ secrets.STAPACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
          kubectl apply -k .

      # 변경 사항 커밋 및 푸시
      - name: Commit files
        run: |
          cd manifests
          echo "`ls`"
          git config --global user.email "yiryeong1631@naver.com"
          git config --global user.name "leeyiryeong"
          git commit -am "Update image tag"
          git push -u origin main

